name: "Sync"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          rm -rf .temp
          git clone -q --single-branch --depth=1 --branch=master https://github.com/home-assistant/addons.git .temp
          
      - name: Create local changes
        run: |
          rm -rf .temp/.git
          rm -rf .temp/.github
          rm -rf .temp/.devcontainer
          rm -rf .temp/.vscode

          for d in .temp/* ; do
              if [ -f "$d/config.yaml" ]; then
                sed -i 's/image: ghcr.io/image: ghcr.nju.edu.cn/' $d/config.yaml
                sed -i 's/image: homeassistant/image: dockerproxy.com\/homeassistant/' $d/config.yaml
              fi
          done
          shopt -s extglob
          rm -rf !(.git|.temp)
          shopt -u extglob
          cp -r .temp/* ./
          rm -rf .temp

          echo '{"name":"Official add-ons：镜像加速","url":"https://github.com/home-assistant/addons","maintainer":"Home Assistant"}' >> repository.json


      - name: Commit files
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "Sync."

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}